// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYsnNGL6CwMJALnwzZXobw1-bwaTdtT5U',
    appId: '1:792437091451:web:d358e8a798f6e9014106de',
    messagingSenderId: '792437091451',
    projectId: 'cap102-ee6f6',
    authDomain: 'cap102-ee6f6.firebaseapp.com',
    storageBucket: 'cap102-ee6f6.appspot.com',
    measurementId: 'G-D5M5B4MX98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLu0wNmeANVAwGJLpGC5tBLOQVOWw61mQ',
    appId: '1:792437091451:android:4426e3e2bd4d5afa4106de',
    messagingSenderId: '792437091451',
    projectId: 'cap102-ee6f6',
    storageBucket: 'cap102-ee6f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7mdjZL-vId_jcc4pX6DhbgEDQsTGTb5k',
    appId: '1:792437091451:ios:5c20ab3fa6674ea34106de',
    messagingSenderId: '792437091451',
    projectId: 'cap102-ee6f6',
    storageBucket: 'cap102-ee6f6.appspot.com',
    iosBundleId: 'com.example.cap102',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7mdjZL-vId_jcc4pX6DhbgEDQsTGTb5k',
    appId: '1:792437091451:ios:5c20ab3fa6674ea34106de',
    messagingSenderId: '792437091451',
    projectId: 'cap102-ee6f6',
    storageBucket: 'cap102-ee6f6.appspot.com',
    iosBundleId: 'com.example.cap102',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYsnNGL6CwMJALnwzZXobw1-bwaTdtT5U',
    appId: '1:792437091451:web:bf802e24f530050f4106de',
    messagingSenderId: '792437091451',
    projectId: 'cap102-ee6f6',
    authDomain: 'cap102-ee6f6.firebaseapp.com',
    storageBucket: 'cap102-ee6f6.appspot.com',
    measurementId: 'G-31RR6FWC10',
  );
}
